# test how sparse matrices work 
- what data structure you re using from simpy 
- minimal way of changing it 

In [70]:
import numpy as np
from scipy.sparse import coo_matrix
import scipy as sp
from scipy.sparse.linalg import svds

d = np.array([3, 4, 5, 7, 2, 6]) 
r = np.array([0, 0, 1, 1, 3, 3]) 
c = np.array([2, 4, 2, 3, 1, 2]) 
b = []
coo = coo_matrix((d, (r, c)), shape=(4, 5))

u, s, vt = svds(coo, k=min(coo.shape)-1, which='SM')

tol = 1e-12
null_mask = s < tol
null_vec = vt.T[:, null_mask]

prod = coo @ null_vec

print("coo", coo, "\nvt.t", vt.T, "\ns", s, "\nnull_vec", null_vec, sep="\n")
print(np.allclose(prod, np.zeros(prod.shape), tol))
# print(coo.toarray())

coo
<COOrdinate sparse matrix of dtype 'int64'
	with 6 stored elements and shape (4, 5)>
  Coords	Values
  (0, 2)	3
  (0, 4)	4
  (1, 2)	5
  (1, 3)	7
  (3, 1)	2
  (3, 2)	6

vt.t
[[-3.65122502e-16  5.51868603e-17  1.33095320e-16]
 [ 1.02537852e-01 -3.58581548e-01  2.19307269e-01]
 [ 8.04805132e-01 -2.53491345e-01  4.44655666e-01]
 [ 5.72683363e-01  2.42961639e-01 -7.52944730e-01]
 [ 1.17509375e-01  8.64945694e-01  4.32735362e-01]]

s
[5.86970066e-16 3.53314821e+00 5.32264566e+00]

null_vec
[[-3.65122502e-16]
 [ 1.02537852e-01]
 [ 8.04805132e-01]
 [ 5.72683363e-01]
 [ 1.17509375e-01]]
False


In [73]:
v = []
r = []
c = []
for col, expansion in enumerate([1, 2, 3]):
    for row, coeff in enumerate([1, 2, 0, 3]):
        if coeff != 0:
            v.append(coeff)
            r.append(row)
            c.append(col)

coo = coo_matrix((np.array(v), (np.array(r), np.array(c))), shape=(4, 3))
print(coo)

<COOrdinate sparse matrix of dtype 'int64'
	with 9 stored elements and shape (4, 3)>
  Coords	Values
  (0, 0)	1
  (1, 0)	2
  (3, 0)	3
  (0, 1)	1
  (1, 1)	2
  (3, 1)	3
  (0, 2)	1
  (1, 2)	2
  (3, 2)	3
