In [ ]:
#test how sparse matrices work 
-what data structure you re using from simpy 
minimal way of changing it 

In [68]:
import numpy as np
from scipy.sparse import coo_matrix
import scipy as sp
from scipy.sparse.linalg import svds

d = np.array([3, 4, 5, 7, 2, 6]) 
r = np.array([0, 0, 1, 1, 3, 3]) 
c = np.array([2, 4, 2, 3, 1, 2]) 
b = []
coo = coo_matrix((d, (r, c)), shape=(4, 5))

u, s, vt = svds(coo, k=min(coo.shape)-1, which='SM')

tol = 1e-12
null_mask = s < tol
null_vec = vt.T[:, null_mask]

prod = coo @ null_vec

print("coo", coo, "\nvt.t", vt.T, "\ns", s, "\nnull_vec", null_vec, sep="\n")
print(np.allclose(prod, np.zeros(prod.shape), tol))
# print(coo.toarray())

coo
<COOrdinate sparse matrix of dtype 'int64'
	with 6 stored elements and shape (4, 5)>
  Coords	Values
  (0, 2)	3
  (0, 4)	4
  (1, 2)	5
  (1, 3)	7
  (3, 1)	2
  (3, 2)	6

vt.t
[[ 1.          0.          0.        ]
 [ 0.          0.35858155 -0.21930727]
 [ 0.          0.25349134 -0.44465567]
 [ 0.         -0.24296164  0.75294473]
 [ 0.         -0.86494569 -0.43273536]]

s
[0.         3.53314821 5.32264566]

null_vec
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]]
True
